#!/bin/bash

set -euo pipefail

docker build -t 3pl_integration -f Dockerfile .
docker tag -f 3pl_integration:latest 914794084459.dkr.ecr.us-east-1.amazonaws.com/3pl_integration:latest
docker push 914794084459.dkr.ecr.us-east-1.amazonaws.com/3pl_integration:latest
